version: '2'
services:
  web:
    build:
      context: .
      args:
        - GITHUB_TOKEN
    volumes:
      - .:/app
    links:
      - solr
      - database
    environment:
      - GITHUB_TOKEN

  varnish:
    image: quay.io/inviqa_images/drupal8-varnish:4.0
    links:
      - web

  solr:
    image: quay.io/inviqa_images/drupal8-solr:4.10

  database:
    image: quay.io/inviqa_images/mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
