version: '2'
services:
  web:
    build:
      context: .
      args:
        - GITHUB_TOKEN
        - CODE_OWNER=build
        - CODE_GROUP=build
        - APP_GROUP=www-data
    volumes:
      - .:/app
    links:
      - solr
      - database
    environment:
      - GITHUB_TOKEN
      - APP_USER_LOCAL=true
      - DRUPAL_HASH_SALT
      - DRUPAL_DATABASE_NAME
      - DRUPAL_DATABASE_USERNAME
      - DRUPAL_DATABASE_PASSWORD
      - DRUPAL_DATABASE_PREFIX
      - DRUPAL_DATABASE_HOST
      - DRUPAL_DATABASE_PORT
      - DRUPAL_CONFIG_DIRECTORY_SECRET

  varnish:
    image: quay.io/continuouspipe/varnish4:v1.0
    links:
      - web

  solr:
    image: quay.io/continuouspipe/drupal8-solr4:v1.0
    volumes:
      - solr_data:/usr/local/share/solr/d8/data/

  database:
    image: quay.io/continuouspipe/mysql5.6:v1.0
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

volumes:
  solr_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m,uid=1000
