version: '2'
services:
  web:
    build:
      context: .
      args:
        - GITHUB_TOKEN
        - CODE_OWNER=build
        - CODE_GROUP=build
        - APP_USER=www-data
        - APP_GROUP=www-data
    volumes:
      - .:/app
    links:
      - solr
      - database
    environment:
      - GITHUB_TOKEN
      - APP_USER_LOCAL=true
      - DRUPAL_HASH_SALT=sosecret
      - DRUPAL_DATABASE_NAME=drupaldb
      - DRUPAL_DATABASE_USERNAME=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal
      - DRUPAL_DATABASE_HOST=database
      - DRUPAL_DATABASE_PORT=3306
      - DEVELOPMENT_MODE=1
    expose:
      - 80
      - 443

  varnish:
    image: quay.io/continuouspipe/varnish4:v1.0
    links:
      - web

  solr:
    image: quay.io/continuouspipe/drupal8-solr4:v1.0
    volumes:
      - solr_data:/usr/local/share/solr/d8/data/
    expose:
      - 8983

  database:
    image: quay.io/continuouspipe/mysql5.6:v1.0
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    expose:
      - 3306

volumes:
  solr_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m,uid=1000
