version: '2'
services:
  web:
    build:
      context: .
      args:
        - GITHUB_TOKEN
        - CODE_OWNER=build
        - CODE_GROUP=build
        - APP_GROUP=www-data
    volumes:
      - .:/app
    links:
      - solr
      - database
    environment:
      - GITHUB_TOKEN
      - APP_USER_LOCAL=true

  varnish:
    image: quay.io/continuouspipe/drupal8-varnish:4.0_v1
    links:
      - web

  solr:
    image: quay.io/continuouspipe/drupal8-solr:4.10_v1
    volumes:
      - solr_data:/usr/local/share/solr/d8/data/

  database:
    image: quay.io/continuouspipe/mysql:5.6_v1
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

volumes:
  solr_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m,uid=1000
