web:
  build: .
  volumes:
    - .:/app
  links:
    - database
  environment:
    GITHUB_TOKEN:

solr:
  image: quay.io/inviqa_images/drupal8-solr:6.2

varnish:
  image: quay.io/inviqa_images/drupal8-varnish:4.0
  links:
    - web

database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
